# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Release version number'
        # Default value if no value is explicitly provided
        default: '1.0.0'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello V${{ inputs.name }}"
      
  create_release_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release Branch
        run: |
          git checkout dev
          git pull
          git checkout -b release-${{ inputs.name }}
          git push --set-upstream origin release-${{ inputs.name }}

  merge_release_to_main:
    needs: create_release_branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Release to Main
        run: |
          git checkout main
          git merge --no-ff release-${{ inputs.name }} -m "Merge release-${{ inputs.name }} into main"
          git tag -a v${{ inputs.name }} -m "Version${{ inputs.name }}"
          git push origin main --tags
